// Generated by CoffeeScript 1.6.3
(function() {
  var test, testText;

  test = require('../index.js');

  testText = "it('should be able to run a case',function(done){  console.log('hello mocha');  assert(true);  done();});it('should be able to fail a case',function(done){  assert(false);  done();});";

  test.test({
    test: testText
  }, function(e, o) {
    return console.log(o.file);
  });

}).call(this);

/*
//@ sourceMappingURL=run.map
*/
