// Generated by CoffeeScript 1.12.7
(function() {
  var fs, test, testText;

  test = require('../index.js');

  fs = require('fs');

  testText = fs.readFileSync('test/test.txt');

  test.test({
    test: testText
  }, function(e, o) {
    return console.log(o.output);
  });

}).call(this);
