// Generated by CoffeeScript 1.6.3
(function() {
  var assert, test, testText, testText2;

  test = require('../index.js');

  assert = require('assert');

  testText = "it('should be able to run a case',function(){  assert(true)})";

  testText2 = "it('should be able to fail a case',function(){  assert(false)})";

  it('should be able to run test', function(done) {
    return test.test({
      test: testText
    }, function(e, o) {
      console.log(o.getLog());
      return done();
    });
  });

  it('should be able to run test', function(done) {
    return test.test({
      test: testText2
    }, function(e, o) {
      console.log(o.getLog());
      return done();
    });
  });

}).call(this);

/*
//@ sourceMappingURL=test.map
*/
